// Central configuration for CRM modules with concise, premium SaaS descriptions.
// Each entry drives: sidebar label, descriptions, API endpoint, table columns, form fields,
// and Kanban Board column grouping properties.

const entityConfig = {
  leads: {
    label: 'Leads',
    title: 'Leads',
    description: 'Capture, qualify, and convert your most promising opportunities.',
    idField: 'id',
    statusField: 'lead_status',
    titleField: 'lead_name',
    subtitleField: 'company_name',
    columns: ['lead_name', 'company_name', 'email', 'phone', 'source', 'lead_status', 'assigned_to'],
    fields: [
      { name: 'lead_name', label: 'Lead Name', type: 'text', required: true },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'source', label: 'Source', type: 'select', options: ['Website', 'Referral', 'Social Media', 'Email Campaign', 'Walk-in'] },
      { name: 'interested_in', label: 'Interested In', type: 'text' },
      { name: 'lead_status', label: 'Lead Status', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Lost'] },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
    ]
  },
  contacts: {
    label: 'Contacts',
    title: 'Contacts',
    description: 'Keep every customer relationship organized and accessible.',
    idField: 'id',
    statusField: 'relationship',
    titleField: 'contact_name',
    subtitleField: 'company_name',
    columns: ['contact_name', 'company_name', 'email', 'phone', 'designation', 'relationship'],
    fields: [
      { name: 'contact_name', label: 'Contact Name', type: 'text', required: true },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'relationship', label: 'Relationship', type: 'select', options: ['Client', 'Vendor', 'Partner', 'Other'] },
      { name: 'address', label: 'Address', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ]
  },
  accounts: {
    label: 'Accounts',
    title: 'Companies & Accounts',
    description: 'Manage client companies, organization profiles, and account owners.',
    idField: 'id',
    statusField: 'company_size',
    titleField: 'company_name',
    subtitleField: 'industry',
    columns: ['company_name', 'industry', 'website', 'address', 'gst_tax_id', 'company_size', 'account_owner'],
    fields: [
      { name: 'company_name', label: 'Company Name', type: 'text', required: true },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'website', label: 'Website', type: 'text' },
      { name: 'address', label: 'Address', type: 'text' },
      { name: 'gst_tax_id', label: 'GST / Tax ID', type: 'text' },
      { name: 'company_size', label: 'Company Size', type: 'select', options: ['1-10', '10-50', '50-200', '200-500', '500+'] },
      { name: 'account_owner', label: 'Account Owner', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ]
  },
  deals: {
    label: 'Deals',
    title: 'Deals & Opportunities',
    description: 'Track opportunities from first contact to successful close.',
    idField: 'id',
    statusField: 'stage',
    titleField: 'deal_name',
    subtitleField: 'account_name',
    valueField: 'value',
    columns: ['deal_name', 'account_name', 'value', 'stage', 'probability', 'expected_close_date'],
    fields: [
      { name: 'deal_name', label: 'Deal Name', type: 'text', required: true },
      { name: 'account_name', label: 'Account Name', type: 'text' },
      { name: 'value', label: 'Value (₹)', type: 'number' },
      { name: 'stage', label: 'Stage', type: 'select', options: ['New Leads', 'Contacted', 'Qualified', 'Proposal Sent', 'Negotiation', 'Closed Won', 'Closed Lost'] },
      { name: 'probability', label: 'Probability (%)', type: 'number' },
      { name: 'expected_close_date', label: 'Expected Close Date', type: 'date' },
      { name: 'source', label: 'Source', type: 'text' },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
    ]
  },
  tasks: {
    label: 'Tasks',
    title: 'Tasks & Activities',
    description: 'Plan your work, manage priorities, and get things done.',
    idField: 'id',
    statusField: 'status',
    titleField: 'task_name',
    subtitleField: 'related_to',
    columns: ['task_name', 'related_to', 'type', 'due_date', 'priority', 'status'],
    fields: [
      { name: 'task_name', label: 'Task Name', type: 'text', required: true },
      { name: 'related_to', label: 'Related To (Lead/Deal)', type: 'text' },
      { name: 'type', label: 'Type', type: 'select', options: ['Call', 'Email', 'Meeting', 'Other'] },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending', 'In Progress', 'Completed'] },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
    ]
  },
  appointments: {
    label: 'Appointments',
    title: 'Appointments & Meetings',
    description: 'Schedule meetings and stay connected with your customers.',
    idField: 'id',
    statusField: 'status',
    titleField: 'title',
    subtitleField: 'with_person',
    columns: ['title', 'with_person', 'appointment_date', 'appointment_time', 'status'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'with_person', label: 'With', type: 'text' },
      { name: 'appointment_date', label: 'Date', type: 'date' },
      { name: 'appointment_time', label: 'Time', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'Completed', 'Cancelled'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ]
  },
  products: {
    label: 'Products',
    title: 'Products & Services',
    description: 'Catalog your products, services, pricing, and tax rates.',
    idField: 'id',
    statusField: 'status',
    titleField: 'product_name',
    subtitleField: 'category',
    valueField: 'price',
    columns: ['product_name', 'category', 'price', 'unit', 'tax', 'status'],
    fields: [
      { name: 'product_name', label: 'Product Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'price', label: 'Price (₹)', type: 'number', required: true },
      { name: 'unit', label: 'Unit', type: 'text' },
      { name: 'tax', label: 'Tax (%)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Out of Stock'] },
      { name: 'description', label: 'Description', type: 'textarea' },
    ]
  },
  invoices: {
    label: 'Invoices',
    title: 'Invoices & Payments',
    description: 'Manage billing, payments, and outstanding invoices effortlessly.',
    idField: 'id',
    statusField: 'payment_status',
    titleField: 'invoice_number',
    subtitleField: 'client_account',
    valueField: 'amount',
    columns: ['invoice_number', 'client_account', 'invoice_date', 'amount', 'paid_amount', 'due_amount', 'payment_status'],
    fields: [
      { name: 'invoice_number', label: 'Invoice Number', type: 'text', required: true },
      { name: 'client_account', label: 'Client / Account', type: 'text' },
      { name: 'invoice_date', label: 'Invoice Date', type: 'date' },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'amount', label: 'Total Invoice Amount (₹)', type: 'number', required: true },
      { name: 'paid_amount', label: 'Amount Paid by User (₹)', type: 'number' },
      { name: 'payment_status', label: 'Payment Status', type: 'select', options: ['Pending', 'Partially Paid', 'Paid', 'Overdue'] },
      { name: 'payment_mode', label: 'Payment Mode', type: 'text' },
    ]
  },
  quotations: {
    label: 'Quotations',
    title: 'Commercial Quotations',
    description: 'Create, manage, and track professional customer quotations.',
    idField: 'id',
    statusField: 'status',
    titleField: 'quotation_number',
    subtitleField: 'client_name',
    valueField: 'total_amount',
    columns: ['quotation_number', 'client_name', 'project_title', 'total_amount', 'quotation_date', 'valid_until', 'status'],
    fields: [
      { name: 'quotation_number', label: 'Quotation Number', type: 'text', required: true },
      { name: 'client_name', label: 'Client / Company Name', type: 'text', required: true },
      { name: 'project_title', label: 'Project / Proposal Title', type: 'text' },
      { name: 'email', label: 'Client Email', type: 'email' },
      { name: 'phone', label: 'Client Phone', type: 'text' },
      { name: 'total_amount', label: 'Total Amount (₹)', type: 'number', required: true },
      { name: 'quotation_date', label: 'Quotation Date', type: 'date' },
      { name: 'valid_until', label: 'Valid Until', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Sent', 'Accepted', 'Declined', 'Expired'] },
      { name: 'terms', label: 'Terms & Conditions', type: 'textarea' },
    ]
  },
  campaigns: {
    label: 'Campaigns',
    title: 'Marketing Campaigns',
    description: 'Run multi-channel marketing campaigns and track budget ROI.',
    idField: 'id',
    statusField: 'status',
    titleField: 'campaign_name',
    subtitleField: 'type',
    valueField: 'budget',
    columns: ['campaign_name', 'type', 'start_date', 'end_date', 'budget', 'status'],
    fields: [
      { name: 'campaign_name', label: 'Campaign Name', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: ['Email', 'Social Media', 'Google Ads', 'Event', 'Other'] },
      { name: 'start_date', label: 'Start Date', type: 'date' },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'budget', label: 'Budget (₹)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['Planned', 'In Progress', 'Completed', 'Cancelled'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ]
  },
  tickets: {
    label: 'Tickets',
    title: 'Support Tickets',
    description: 'Resolve customer support inquiries and track service tickets.',
    idField: 'id',
    statusField: 'status',
    titleField: 'subject',
    subtitleField: 'client_name',
    columns: ['subject', 'client_name', 'priority', 'status', 'assigned_to', 'created_date'],
    fields: [
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'client_name', label: 'Client Name', type: 'text' },
      { name: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Urgent'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Resolved', 'Closed'] },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
      { name: 'created_date', label: 'Created Date', type: 'date' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ]
  }
};

export default entityConfig;
